### ISSUE TITLE
Window state change to ICONIC on lost focus

### ISSUE THREAD

**Issue by licaon-kter** [KillaW0lf04/The-Witcher-2-Issues#100]
While using i3 ( http://i3wm.org ) as my window manager, and running the game in FULLSCREEN I lose the game window every time I switch to another workspace. 
WINDOWED mode ( *Fullscreen=0* in the **user.ini**) works as expected.

By running the debug version of the debian git builds ( http://i3wm.org/docs/repositories.html ), I traced this a bit:
* using workspace 2
* started the game until I get to the menu
* switch to another workspace say 1 ( WIN+1 )
* switching back to workspace 2 one will see that the game window has disappear, BUT if any other windows (say the Steam client) were there when the game started those are still there, AND more important the game STILL runs, although I can't ever reach its window, I need to *ps* and *kill*-il

Running the debug dump;
> DISPLAY=:0 i3-dump-log | bzip2 -c > /tmp/i3-witcher_1.log.bz2

And grep-ing along, we see the game start:

> 01.02.2015 09:48:45 - handlers.c:handle_map_request:283 - window = 0x02c00014, serial is 4231.
> 01.02.2015 09:48:45 - manage.c:manage_window:165 - Managing window 0x02c00014
> 01.02.2015 09:48:45 - WM_CLASS changed to witcher2 (instance), witcher2 (class)
> 01.02.2015 09:48:45 - WM_NAME changed to "The Witcher 2"
> 01.02.2015 09:48:45 - Using legacy window title. Note that in order to get Unicode window titles in i3, the application has to set _NET_WM_NAME (UTF-8)
> 01.02.2015 09:48:45 - _NET_WM_NAME changed to "The Witcher 2"
...
> 01.02.2015 09:48:45 - ipc.c:ipc_send_window_event:1177 - Issue IPC window focus event (con = 0x1d4b8b0, window = 0x02c00014)

so the game gets *window = 0x02c00014* in container *con = 0x1d4b8b0* (as far as I can read this)

After the game reaches the menu, I switch workspaces:

> 01.02.2015 09:48:48 - commands_parser.c:parse_command:270 - COMMAND: *workspace 1*
> 01.02.2015 09:48:48 - commands.c:cmd_criteria_init:266 - Initializing criteria, current_match = 0x665580
> 01.02.2015 09:48:48 - commands.c:cmd_workspace_name:1065 - should switch to workspace 1
> 01.02.2015 09:48:48 - Creating new workspace "1"

something happens with the container for the workspace where the game window is:

> 01.02.2015 09:48:48 - ClientMessage for window 0x02c00014
> 01.02.2015 09:48:48 - handlers.c:handle_client_message:802 - Client has requested iconic state. Closing this con. (con = 0x1d4b8b0)
> 01.02.2015 09:48:48 - tree.c:tree_close:210 - next = 0x1d4baa0, focused = 0x1d4bc90
> 01.02.2015 09:48:48 - tree.c:tree_close:212 - closing 0x1d4b8b0, kill_window = 0
> 01.02.2015 09:48:48 - ipc.c:ipc_send_window_event:1177 - Issue IPC window close event (con = 0x1d4b8b0, window = 0x02c00014)

and the important bit **Client has requested iconic state. Closing this con. (con = 0x1d4b8b0)** which leads me to this commit: http://code.stapelberg.de/git/i3/commit/?h=next&id=136b3e345bfde637d3270eafaa2d8aa3555cc3d5

Now, did I read the log ok, does the game try to switch to ICON mode when losing focus while FULLSCREEN or at any time? 

If so why? And can you make it stop ? :P

**Comment by vpltd-peterm** [comment]
All of the windowing is currently driven by SDL2, so you would be best checking the source code to SDL2.

It is completely out of our scope to support every window manager out there. Incidentally, if it is impossible to un-iconify an iconified window in that window manager, then i would consider that a bug in the window manager.

**Comment by licaon-kter** [comment]
Now, I got a fix for this it's setting the game to run, in the Steam command line as:
> SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%

or in the console

> export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
> LD_LIBRARY_PATH=~/.steam/bin32/ ~/.steam/bin32/steam-runtime/run.sh ./witcher2

But I believe this can be better forced on your end, I see no point of the current behaviour (and since it looks like it's the default one https://github.com/ValveSoftware/Source-1-Games/issues/462 makes it even worse). The only reason this could be useful is that maybe the game pauses and it (hopefully) does not use resources when minimized.

**Comment by vpltd-peterm** [comment]
This has more to do with the behavior of SDL2 than it does of our game. In the future we plan to migrate away from SDL2 for other reasons, but I am afraid the case for making changes such as this is small at the moment.

**Comment by licaon-kter** [comment]
Fixed in i3 by reverting that commit: https://github.com/i3/i3/issues/1516#ref-commit-d551618
