### ISSUE TITLE
Ubuntu 14.04 - Crash at startup (when xboxdrv is running)

### ISSUE THREAD

**Issue by melo0187** [KillaW0lf04/The-Witcher-2-Issues#11]
I'm running Ubuntu 14.04 64-bit with Steam (non-beta) and was not able to launch the game ever since it's release on Linux the 22nd of May. The update from yesterday did not change anything in this regard.

Running ldd returns the following:
```
melo@melo-desktop:~$ ldd "/home/melo/.local/share/Steam/SteamApps/common/the witcher 2/witcher2" | grep not
	libSDL2-2.0.so.0 => not found
	libSDL2_image-2.0.so.0 => not found
	libsteam_api.so => not found
	libcurl.so.4 => not found
```

**Comment by vpltd-peterm** [comment]
Closed due to no feedback, believed fixed
