### ISSUE TITLE
Crash with latest git mesa

### ISSUE THREAD

**Issue by gutigen** [KillaW0lf04/The-Witcher-2-Issues#18]
Game crashes at start (after launcher) without any output at all.

Using Ubuntu 14.04 with latest mesa git from https://launchpad.net/~oibaf/+archive/graphics-drivers on HD7770.

Yes, I know AMD is not supported yet. Is there any way to get some data about this issue?

**Comment by vpltd-peterm** [comment]
AS this is about a quite old release of the game now, and I have feedback suggesting more recent versions of mesa are more capable, i'm closing this one. At last check, r600 is complete enough to run Witcher 2, but radeonsi is not. YMMV.
