### ISSUE TITLE
Audio sometimes fails

### ISSUE THREAD

**Issue by NotMrFlibble** [KillaW0lf04/The-Witcher-2-Issues#19]
I've noticed that, sometimes, audio glitches (short breaks) occur; some time later, the audio will cease altogether with a short burst of noise at around the same volume level as the preceding audio. While I have not observed all of the effects following this, it <i>appears</i> that set-piece speech requires that you click to advance.

**Comment by vpltd-peterm** [comment]
Closing due to no feedback, believed fixed since the switch to openal-soft
