### ISSUE TITLE
Crash to Desktop 

### ISSUE THREAD

**Issue by retiree** [KillaW0lf04/The-Witcher-2-Issues#25]
Hello,

The game crashes after a few minutes.  It crashes while in the tutorial and in the game.  I could not get past the prologue. 

Thanks for any help and good luck to the team who brought this to Linux!

Ubuntu 14.04
Nvidia GTX 460
32 bit
8GB RAM

Here is the beginning of the crash report (Sorry, I'm not sure how to paste the entire report without ruining this post):

https://gist.github.com/KillaW0lf04/43c060deedb3dd38a70b

**Comment by vpltd-peterm** [comment]
Closing due to incomplete crash report
