### ISSUE TITLE
Crash on startup due to missing lib32-libcurl.so.4 dependancy "CURL_OPENSSL_3"

### ISSUE THREAD

**Issue by anadon** [KillaW0lf04/The-Witcher-2-Issues#30]
I cannot start up the witcher 2 on my system due to arch's curl package being newer than 7.23, after which CURL_OPENSSL_3 was removed.

**Comment by vpltd-peterm** [comment]
Closed, as it is a distro dependancy issue, and the discussion turned into a distro flame war.
