### ISSUE TITLE
Slow and stuttery…

### ISSUE THREAD

**Issue by NotMrFlibble** [KillaW0lf04/The-Witcher-2-Issues#44]
The current beta (353083) is slow and stuttery from the start; the video at the start is displayed at, typically, 10fps instead of the expected 60fps or higher. The current stable release (292707), while it works slowly in some instances, is at least smooth.

SteamOS runtime environment, Debian testing desktop environmnent, stock Debian testing/unstable Mesa 10.2.4 radeonsi in both cases. Kernel is 3.16. Environment contains `GALLIUM_HUD=cpu+fps R600_DEBUG=hyperz`.

**Comment by vpltd-peterm** [comment]
Closing as driver issue
