### ISSUE TITLE
beta4 - crash running around

### ISSUE THREAD

**Issue by adamdmoss** [KillaW0lf04/The-Witcher-2-Issues#46]
Performance is pretty great nowadays, but stability's always been quite poor here.

Ubuntu 14.04.1 LTS - 64 bit - fairly fresh install.
OpenGL renderer string: GeForce GTX 480/PCIe/SSE2
OpenGL core profile version string: 4.3.0 NVIDIA 331.38

Release through to Beta 2 were prone to crashing between areas, Beta 3 seemed pretty good for stability, Beta 4 makes my GPU fans rev up madly as I run around and then the whole app crashes, not between areas but just running around, and with no crash report prompt.

Any info I can provide to help?

**Comment by vpltd-peterm** [comment]
Clean exits as reported by this log are quite often the game itself exiting. Unfortunately, there are a few bugs in the original game itself which are outside of our scope to fix.
