### ISSUE TITLE
Mouse is erratic and unpredictable [Beta4]

### ISSUE THREAD

**Issue by CommanderAlchemy** [KillaW0lf04/The-Witcher-2-Issues#48]
This is from my post in the input delay but then i think this is not related to that issue so i created this one and also recorded the issue that is uploading to youtube.

#### Issue:
For me the mouse skips or just behaves odd. moving in a circle the mouse sometimes does not move or just stops for a moment in some direction making it move a bit erratic and unpredictable. 

When moving the mouse left and right in a horizontal way it seems to accelerate / decelerate and stutter and seem to pull in the top left direction.  

#### The video: 
1st' I start moving the mouse fast in circles (the prettiest i can make) and it moves all over the screen.
2' I start moving the mouse slowly in circles (going well)
3' I start accelerating the movement and the mouse just freaks out as shown in the video.

##### Steam systeminfo:
https://gist.github.com/CommanderAlchemy/83c70f2deffb678192c3
##### Mouse: 
Logitech G9x running mouse polling at 1000Hz

#### Video:

[![Mouse issues with Witcher 2 on Linux Beta 4](http://img.youtube.com/vi/LdXE3q9O2kY/0.jpg)](http://www.youtube.com/watch?v=LdXE3q9O2kY)

**Comment by vpltd-peterm** [comment]
Hardware issue, closing

**Comment by Hubro** [comment]
I would hardly boil this down to just a hardware issue. No other game I've ever played reacted so badly to a 125hz polling rate, not even on Linux. It was completely unplayable.

**Comment by vpltd-peterm** [comment]
We use the events the system gives us through X11/SDL2. If those events are wrong, there is nothing we can do about it.

There is obviously some sort of fundamental system problem if 1000Hz is fine, and normal mice are also fine, and if USB 2.0 and 3.0 ports behave differently.

**Comment by Hubro** [comment]
Sorry for being persistent, but are you completely positive the events are wrong? I play lots of other games, some or all of which has to use SDL, without setting my mouse to "gaming mode" (1000Hz) and none of them suffer from this issue.

There has to be a bug here somewhere, and whether it is in SDL2 or a specific interaction between SDL2 and your code, it would be a shame if it wasn't found and squashed.

List of games I'm currently playing that don't suffer from this issue:
* Metro 2033 redux
* Dota 2
* Don't starve
* Starbound
* Forced
