### ISSUE TITLE
won't start - Dell Inspiron 3537 with Ubuntu 14.04, AMD 8850M

### ISSUE THREAD

**Issue by yuvii** [KillaW0lf04/The-Witcher-2-Issues#63]
It crashes immediately upon clicking "launch game".

I'm running Ubuntu 14.04.01 LTS 64-bit on a Dell Inspiron 3537 laptop, graphics card is AMD Radeon HD 8850M, and the computer has an Intel Core-i7 processor. Other steam products worked fine till now. Here's the [crash report](http://www.codeshare.io/IJXAa).

The computer uses the AMD graphics driver (when checking the "additional drivers" it says so, and also `lspci | grep VGA` ), but after [asking for help](http://steamcommunity.com/app/20920/discussions/0/34095132076919710/) in game discussions I was told it was trying to use the Intel GPU for some reason (the output of [glxinfo](http://www.codeshare.io/t7jZZ) also says that...). 

Their suggestions their didn't help me very much as I don't want to mess too much with the BIOS or graphics settings (and I'm completely confused about the whole what graphic card is being used thing)

**Comment by vpltd-peterm** [comment]
Not a game issue, but a setup issue. Closing.
