### ISSUE TITLE
Switch the launcher to Qt 5 or GTK 3 to prepare for upcoming Wayland support

### ISSUE THREAD

**Issue by shmerl** [KillaW0lf04/The-Witcher-2-Issues#70]
Not an urgent issue, just an enhancement proposal. GTK 2 is being phased out, so it's worth avoid using it going forward and switch to Qt 5 or GTK 3 for the launcher UI needs. This will help reducing dependencies on X11 and switch to the upcoming Wayland.

**Comment by vpltd-peterm** [comment]
At the time GTK2 was chosen because it was present in the Steam runtime, and our concern ensuring that the configuration tool would work on SteamOS. It turned out that for SteamOS it was better to create a "tenfoot" launcher/configuration tool.

It's unlikely we'll change it now, but future projects going forward will use GTK3.

**Comment by shmerl** [comment]
Will you update TW2 in general when SteamOS will switch to Wayland? It's unlikely to happen very soon, but it might happen within a year or so, since Nvidia is already preparing to release Wayland drivers.

Using XWayland probably will add some extra overhead.

**Comment by vpltd-peterm** [comment]
For SteamOS it will not matter, as the tenfoot launcher for SteamOS is entirely SDL2 based.

**Comment by shmerl** [comment]
And for other distros? How much does TW2/eON depend on X11 at present?

**Comment by vpltd-peterm** [comment]
Currently we need a few things from X11 directly that SDL2 does not expose. The long term plan for eON is to remove SDL from the picture altogether and go direct to X11.

Realistically, Wayland is not going to be ready to completely replace X11 for a while yet, and certainly not until the nvidia and amd catalyst drivers support it for gaming. When Wayland proves itself good and ready for mainstream use, we will consider supporting it.

**Comment by shmerl** [comment]
That's good enough, thanks. Wayland is actually quite ready to completely replace it (mobile systems already use it in production, for example Sailfish). The lack of drivers however is holding it back and the fact that major DEs like KDE didn't finish adding Wayland support yet. But that's going to change soon it seems. So you can expect it coming and do your research before investing too much effort into replacing SDL with too much X11 dependencies since it can mean double work for you when Wayland will become widely used by all DEs.

**Comment by vpltd-peterm** [comment]
That remains to be seen, but personally I am hoping Wayland DOES replace X11 as quickly as possible.. because quite frankly X11 is crap :)

**Comment by shmerl** [comment]
By the way, what's wrong with SDL2? Is not not efficient enough for functions it provides?

**Comment by vpltd-peterm** [comment]
There are cases where we need more from the underlying window manager - info about border sizes for example. There's also some places where we could just benefit more from being directly involved - such as the whole Xrandr/Xinerama mess...

Hopefully.. a lot of stuff that Wayland will just make go away :D
