### ISSUE TITLE
"Trying to access something that's not a regular file or folder" warnings

### ISSUE THREAD

**Issue by shmerl** [KillaW0lf04/The-Witcher-2-Issues#73]
eon log in `~/.local/share/cdprojektred/witcher2/eon.txt` is filled with warnings like:

`[thread 00000004][W][269]: Trying to access something that's not a regular file or folder: '/opt/games/witcher2/game/bin/config/lang' !`

It seems they appear for each file being red (which probably slows down startup time as well).

Game release: GOG 1.0.0.3 with latest VP patch.
System: Current Debian testing x86_64.
Filesystem: XFS

**Comment by vpltd-peterm** [comment]
The warnings are harmless
