### ISSUE TITLE
Game won't start on OpenSUSE 13.1 - no crash report

### ISSUE THREAD

**Issue by Dalizz** [KillaW0lf04/The-Witcher-2-Issues#76]
GOG version
OpenSUSE 13.1 64bit
C2D E8400, 6Gb RAM
AMD HD6870, Catalyst 14.4 & 14.6 Beta

Game does not start. Black screen flashes and then disappears. No error message besides "Aborted." in console. No difference if windowed mode or fullscreen is selected.
Tried with both 14.4 and 14.6 Beta AMD drivers.

Earlier workarounds for similar problems did not help. No "aaa_base-malloccheck" package installed, updated LLVM to 3.4.2 and libSDL2 to 2.0.3. Otherwise standard OS13.1 installation, no custom kernels etc. All required packages should be installed.

eon.txt here: 
https://gist.github.com/Dalizz/4b780806ad4cc3b2877d

**Comment by vpltd-peterm** [comment]
Need more information as "Aborted" points to something killing our process...

**Comment by Dalizz** [comment]
I have actually upgraded to OpenSUSE 13.2 and now I get his:
https://gist.github.com/Dalizz/cbf724cccc914ca970d9

..which looks similar to this although the kernel version does not match:
https://github.com/KillaW0lf04/The-Witcher-2-Issues/issues/89

Is it the same issue?

I have the GOG.com version so I don't have access to the latest Steam build, I'll have to wait a little longer for patches unfortunately.

**Comment by Dalizz** [comment]
This is now fixed in the latest beta patch for GOG version.
