### ISSUE TITLE
Segfault on Launch with Ubuntu 14.04

### ISSUE THREAD

**Issue by calitidexvii** [KillaW0lf04/The-Witcher-2-Issues#79]
Similar to Issue #2 but different OS and unable to apply same fix. Full error message submitted to reporting system.

Output of command: ''/home/username/.local/share/Steam/SteamApps/common/the witcher 2/crash_reporting/minidump_stackwalk' '/home/username/.local/share/cdprojektred/witcher2//1362f7b1-0d41-d568-44bdf3db-5352fbb7.dmp' '/home/username/.local/share/Steam/SteamApps/common/the witcher 2/crash_reporting/symbols/''
===============================================================================================
Operating system: Linux
                  0.0.0 Linux 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64
CPU: x86
     GenuineIntel family 6 model 70 stepping 1
     1 CPU

Crash reason:  SIGABRT
Crash address: 0xba4

...[Full error message submitted to reporting system]...

===============================================================================================
Output of command: 'glxinfo -l 2>&1'
===============================================================================================
sh: 1: glxinfo: not found
===============================================================================================
[thread ffffffff][I][0]: Log system initialised
[thread ffffffff][I][39]: Default allowed number of simultaneously open files in the system is 2048.
[thread ffffffff][I][39]: Current memlock limit is 65536.
[thread ffffffff][I][39]: setrlimit(RLIMIT_MEMLOCK) failed, (1) Operation not permitted
[thread 00000001][I][101]: OpenGL information:
[thread 00000001][I][101]:     renderer: Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2
[thread 00000001][I][101]:     vendor: Intel Open Source Technology Center
[thread 00000001][I][101]:     version: 3.3 (Core Profile) Mesa 10.1.3
[thread 00000001][I][101]:     GLSL version: 3.30
[thread 00000004][W][524]: Game is trying to enable termination on heap corruption. We don't have it implemented at the moment, implement it? This warning will be issued only once per run.
[thread 00000004][W][553]: eON_LoadLibraryEx() couldn't load 'C:\home\username\.local\share\Steam\SteamApps\common\the witcher 2\bin\telemetry32.dll', returning NULL!
[thread 00000004][W][7412]: REGISTRY OPERATION: RegOpenKeyExW() returns ERROR_NOT_FOUND (subkey not found) key = HKEY_CURRENT_USER, subkey = SOFTWARE\PersonalAudio\MyEars
[thread 00000004][W][12918]: eON_LoadLibraryEx() couldn't load 'LightFX.dll', returning NULL!
[thread 00000004][W][12919]: eON_LoadLibraryEx() couldn't load 'nvapi.dll', returning NULL!
[thread 00000004][W][12973]: eON_LoadLibraryEx() couldn't load 'wintab32.dll', returning NULL!
[thread 00000004][I][13044]: Available video memory: 0
[thread 00000004][I][13044]: Available texture memory: 0
[thread 0000000d][I][13064]: OPENGL: OpenGL thread start
[thread 0000000d][I][13086]: OpenGL backend to Direct3D9: SUMMARY OF FALLBACKS AND INEFFICIENCIES:
[thread 0000000d][I][13086]:  - Anisotropic texture filtering not supported in OpenGL! This may produce incorrect rendering results in game, as other texture filtering modes will be used instead.
[thread 0000000d][I][13086]: OpenGL backend to Direct3D9: END OF SUMMARY

**Comment by vpltd-peterm** [comment]
Closing as it's a driver issue
