### ISSUE TITLE
Logitech Rumblepad2 (wired wersion) not working in-game

### ISSUE THREAD

**Issue by isage** [KillaW0lf04/The-Witcher-2-Issues#81]
I've added line to SDLGamepad.config
(same as for wireless version, just with different id)
Now gamepad recognized in configurator and i can bind buttons, but game still doesn't see it. 
I can't even choose it in options->controls, there's only keyboard.

**Comment by vpltd-peterm** [comment]
Please check this with the latest beta build

**Comment by isage** [comment]
Yep, now it's working. Thank you.
