### ISSUE TITLE
Crash reporting tool fails with SSL error

### ISSUE THREAD

**Issue by Lysius** [KillaW0lf04/The-Witcher-2-Issues#83]
I'm trying to use the automatic crash reporter on Fedora 20, but when I try to send the report, I only get an error message:

curl library request execution failed! Error: 60, error text: "SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"

**Comment by Francis1993Z** [comment]
Same for me on both 20 and 21.

**Comment by vpltd-peterm** [comment]
This is a distro specific problem with libcurl. However, the next release of the game will include an updated crash reporter, which should be able to use the distro's own libcurl rather than insist upon the one from steam-runtime.
