### ISSUE TITLE
Game hard crashes PC in chapter 2, subsequently can not start the game

### ISSUE THREAD

**Issue by sportpeppers** [KillaW0lf04/The-Witcher-2-Issues#84]
Ubuntu 14.04 64-bit 
nVidia Geforce 560Ti
16g ram on an intel cpu
Steam and GOG versions

Summary: 
When I get to a mission transition in chapter 2 the game hard crashes my PC and then the game will no longer launch.

Long version:
The first time this happened to me, the game was running awesome (latest betas are perfect for me performance-wise), but then when playing through chapter 2 i am following the owl the game totally breaks. I've never played this game before so I assume I'm at the end of the scripted mission, and the game completely locks up my PC.

I rebooted and tried launching the game, it looks like it's about to start and then I get a crash window popup with the output that I've pasted below. I tried verifying all the files in steam, they are ok according to steam. I checked the sha5sum I've seen posted here, also fine. Deleted local content, and redownloaded it. No luck. Got frustrated.

Downloaded the GoG version of the game and copied over my savegame files. The game launched and I assumed something broke when the hard crash occurred. I play up to the same point as I was in steam and the game crashed *again* (right as I'm finishing up following the Owl -- I think -- to save the king or whatever). Hard crash, PC completely done for in the *exact* same spot.

After rebooting the GoG version will also no longer launch and crashes just like the steam version. I'm not sure what is getting broken as I've troubleshot the steam version to no avail. Would love some guidance on what to check so I can continue on. Thanks! 

Log: https://gist.github.com/sportpeppers/a9b0f99db0ca3e120ab2

**Comment by vpltd-peterm** [comment]
Hardware problem, closing.

**Comment by psi29a** [comment]
It could have been drive thrashing by paging out to disk, making the system appeared locked. If this person can validate that the drive light is solid, and they have a many saves, then it might be time to clean those saves out and try again.
