### ISSUE TITLE
steamclient.so not found even though it IS at the right place

### ISSUE THREAD

**Issue by Lykos** [KillaW0lf04/The-Witcher-2-Issues#86]
I am running Ubuntu 14.04 on a 64 bit machine. I already had a different problem before which seems to be very common but which I managed to solve:
It crashed without any useful message. It turned out that it didn't find libSDL and libcurl. I changed the launcher command to

  LD_LIBRARY_PATH=/home/myname/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu %command%

After that, at least this problem seems to be solved, but now I get a window telling me:

  Please make sure Steam client is running, and currently logged-in Steam account has the game in Library. The game will now exit.

When I ran it on the command line using "~/.steam/steam/SteamApps/common/the witcher 2/witcher2
" (again setting LD_LIBRARY_PATH as above), I got the same behaviour, i.e. it showed the above message after some time. However, it additionally gave the following output on the terminal:

  [S_API FAIL] SteamAPI_Init() failed; Sys_LoadModule failed to load: /home/myname/.steam/bin32/steamclient.so
  [S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.

Apparently this happened to other people on the internet as well, but in those cases, it was just looking for the library in the wrong place. But I checked the given path and the steamclient.so WAS there. Adding the directory to LD_LIBRARY path didn't make any difference (neither in the launcher nor on command line) I didn't find any information on what people did if they had this problem. Note that Ubuntu set up the paths so that everything seems to be in /home/myname/.steam and not in /home/myname/.local/steam as for some other people.

**Comment by vpltd-peterm** [comment]
Not a problem with the game, but more a problem with Steam and it's environment. Closing.
