### ISSUE TITLE
Public beta (feb. 24.) won't start

### ISSUE THREAD

**Issue by eydee** [KillaW0lf04/The-Witcher-2-Issues#93]
### Description:
When launching the game from steam, the launcher appears and works, however, the game itself won't start.

### Related terminal output:
ERROR - eON failed to initialise!

### eon.txt:
[thread ffffffff][I][0]: Log system initialised
[thread ffffffff][I][0]: Default allowed number of simultaneously open files in the system is 2448.
[thread ffffffff][I][0]: Current memlock limit is 65536.
[thread ffffffff][I][0]: setrlimit(RLIMIT_MEMLOCK) failed, (1) Operation not permitted
[thread ffffffff][I][2]: setup_teb_register() - using LDT entry 13

### System info:
Freshly installed and updated Fedora 21 x86_64 (kernel: 3.17.8-300.fc21.x86_64)
Phenom II X4 810
4GB DDR2
Radeon 6850 using open source drivers
(libgcc_s.so*, libstdc++.so*, libxcb.so* files removed from the steam runtime as they conflict with the Radeon driver due to being outdated.)

**Comment by vpltd-peterm** [comment]
I will look into this, it is a failure early on so it is probably related to the new LDT code

**Comment by vpltd-peterm** [comment]
Strange, the game runs OK on Fedora 20, kernel 3.17.8-200.fc20.x86_64, using the nvidia drivers
Will add some more logging to see if we can see where this trips up exactly,at this point I can only think it is something to do with the mesa driver

**Comment by fredoche** [comment]
I ran the latest beta as well and have the same console output. I am running fedora 21 with the radeon driver.

**Comment by vpltd-peterm** [comment]
OK, i've made a small update (BuildID 503570) which adds some extra logging around this area. Please run it and submit the resulting eon.txt log

**Comment by nickj7** [comment]
I am seeing the same issue on Ubuntu 14.10 64 bit, kernel 3.16.0-29-generic #39-Ubuntu SMP. Using open source radeon drivers from oifab git

Running the build 503570. I get the same error:

ERROR - eON failed to initialise!
Game removed: AppID 20920 "The Witcher 2: Assassins of Kings Enhanced Edition", ProcID 6901


Eon.txt:

[thread ffffffff][I][0]: Log system initialised
[thread ffffffff][I][0]: Default allowed number of simultaneously open files in the system is 2448.
[thread ffffffff][I][0]: Current memlock limit is 65536.
[thread ffffffff][I][0]: setrlimit(RLIMIT_MEMLOCK) failed, (1) Operation not permitted
[thread ffffffff][I][2]: setup_teb_register() - using LDT entry 13
[thread 00000001][E][70]: PrepareOpenGLDisplayInformation() failed!!

**Comment by vpltd-peterm** [comment]
OK, this is probably our GL detection code failing to handle r600. Does the game start correctly in OpenGL 2.1 mode ? (use the command switch --eon_opengl21 to force the game to use it)

**Comment by eydee** [comment]
I tested now, I have the same eon.txt output as posted above. Switching to GL2.1 seems a bit problematic. Putting the option into the Steam launch options doesn't do anything (Is it passed to the launcher which doesn't pass on? It should.). The OGL option in the launcher doesn't work at all. (Maybe worth another bug report?). However, if I launch the game binary directly, the behavior is different:

Without the switch:
eON failed to initialise!

With the switch:
Steam cannot be found/loaded dialog box.

So the GL2.1 code would work if the game was launched by Steam, with all library paths set up correctly. It goes beyond the point where it crashed previously.

**Comment by vpltd-peterm** [comment]
For launching the game with the steam runtime, i have found the following works:
LD_LIBRARY_PATH=~/.steam/bin32/ ~/.steam/bin32/steam-runtime/run.sh ./witcher2

Yes that's quite a mouthful but it is the only way to see that steam_api.so (and later steamclient.so) get the dependencies they need.

Alternatively you can delete/rename the "launcher" file, and symlink it to "witcher2" to skip the launcher and run the game directly from Steam.

It sounds odd that the MESA driver is not capable of creating a GL 3.2 context, though...

**Comment by vpltd-peterm** [comment]
Can you confirm with the configuration for GL version set to "Auto", the game does not run for you?

**Comment by eydee** [comment]
Yes, I can confirm it. No matter if I set the GL renderer in the launcher to OGL2, OGL3 or auto, it tries to use OGL3 and exits with "eON failed to initialise!".

I tried the command line mentioned above:
LD_LIBRARY_PATH=~/.steam/bin32/ ~/.steam/bin32/steam-runtime/run.sh ./witcher2 --eon_opengl21

It starts and seems to work. Menus are a bit sluggish, but once the game loads performance seems to be what it usually is.

**Comment by vpltd-peterm** [comment]
OK, we think this is a problem with MESA, because what we are doing now is asking for an OpenGL Core context, whatever the highest the driver can provide is. We then check what version it said it can provide. As long as it's 3.2 or higher, it should work as before. However, MESA just immediately seems to fail, and our fallback to a non-Core context isnt working.

I will fix the fallback option, but really we need to see why MESA is failing on asking for a Core context. I will note that the nVidia binary driver, and AMD Catalyst do not have any problem here, and work correctly.

**Comment by eydee** [comment]
It is strange, because GL3-only games (like all Source games) work fine. Current Mesa provides OpenGL 3.3 by the way.

I tried Ubuntu 14.04 now for comparison. The public beta crashes with the same "eON failed to initialise!" message. (eon.txt contents are the same as well.) The non-beta crashes too, though in a very different fashion.

I would say it might indeed be a Mesa/Radeon issue. In that case, fixing the fallback option will be OK. (Please add a terminal output message when GL2 is being used, so we can see if the fallback happens. It will be useful for testing future driver versions and for Mesa developers if they want to look into this.)

# non-beta eon.txt:
http://pastebin.com/MBrSFxqA

# non-beta crash log:
http://pastebin.com/L8G5YUkM

# glxinfo from Fedora 21:
http://pastebin.com/XD6VFM50

# glxinfo from Ubuntu 14.04 LTS:
http://pastebin.com/5sF3iKf2

**Comment by vpltd-peterm** [comment]
It depends how the games are asking for those features - are they creating a Core context and asking for 3.2, or are they just creating a regular context and asking for all the GL extensions manually?

We do both of these, the 3.2 mode does the former, the 2.1 mode does the latter.

**Comment by eydee** [comment]
I don't know, I'm not the developer of them. From my point of view, they just work.

The only thing I can add is that now I tested both version of this game with fglrx, and both works indeed. Ubuntu has older kernel and xorg versions so it can be used. However, Fedora, Arch etc. users cannot use fglrx, so the game won't work for them. (Or it will with the fallback only.) When Ubuntu catches up, more people might face with the same problem.

Let me know if I can provide more info.

**Comment by tomtomme** [comment]
maybe contact the mesa devs on #dri-devel channel on irc.freenode.net
I can confirm that fglrx works while radeonsi fails with the new beta

**Comment by kaydenl** [comment]
Hello.  I am one of the Mesa developers.

You appear to be calling glXCreateContextAttribsARB with an attribute list of:
GLX_CONTEXT_MAJOR_VERSION_ARB, 2,
GLX_CONTEXT_MINOR_VERSION_ARB, 1,
GLX_CONTEXT_PROFILE_MASK_ARB, GLX_CONTEXT_CORE_PROFILE_BIT

According to the GLX_ARB_create_context specification,
"If the requested OpenGL version is less than 3.2, GLX_CONTEXT_PROFILE_MASK_ARB is ignored and the functionality of the context is determined solely by the requested version."

So, since you requested a GL 2.1 core profile context (which never existed!), we ignored your profile request and instead gave you a legacy GL context.  This is correct, but perhaps surprising.

The fix is easy: ask for 3.2 core profile, or ask for 2.1 with no profile.

**Comment by vpltd-peterm** [comment]
OK, i will look into this more. We dont explicitly ask for any version when we ask for a GL Core context, but maybe SDL2 decides behind our back.

It could also be that something went wrong asking for a 3.2 Core context, and then when we asked for 2.1 legacy, SDL forgot to clear the Core bit.

Oddly enough, the nvidia and AMD catalyst drivers do work !!

**Comment by kaydenl** [comment]
Ah - looking at SDL_video.c, it seems that the version defaults to 2.1.  Apparently, calling SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE) sets the profile, but doesn't change the version.  So you'd have to also request a version.

Making SDL automatically bump the version up to 3.2 (unless it was already higher) when requesting a core profile might be a nice improvement, and help avoid this sort of trouble.

Thanks!

**Comment by vpltd-peterm** [comment]
Originally we set 3.2 when we ask for a core profile context, and im going to revert to doing that for Witcher 2 now. We have a D3D10/11 renderer in progress that requires higher than this, though. It seems we will need a rethink long term about how we set up GL.

We're also wondering if the 2.1 fallback is even necessary these days, but we'll see...

**Comment by mwoodj** [comment]
The public beta fails to start for me on Gentoo 64-bit. The launcher works but starting the game just results in a couple of seconds of activity and then it quits. Changing the renderer has no effect.

The CrashReporter does not run against the 32-bit glibc in steam runtime:

/sgraid1/home/mwoodj/.local/share/Steam-HDD/SteamApps/common/the witcher 2/CrashReporter: /home/mwoodj/.steam/bin32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /sgraid1/home/mwoodj/.local/share/Steam-HDD/SteamApps/common/the witcher 2/CrashReporter)

**Here is the eon.txt:**

[thread ffffffff][I][0]: Log system initialised
[thread ffffffff][I][0]: Default allowed number of simultaneously open files in the system is 1024.
[thread ffffffff][I][0]: Current memlock limit is 65536.
[thread ffffffff][I][0]: setrlimit(RLIMIT_MEMLOCK) failed, (1) Operation not permitted
[thread ffffffff][I][110]: setup_teb_register() - using LDT entry 13
[thread 00000001][I][198]: OpenGL information:
[thread 00000001][I][198]:     renderer: GeForce GTX 670/PCIe/SSE2
[thread 00000001][I][198]:     vendor: NVIDIA Corporation
[thread 00000001][I][198]:     version: 4.5.0 NVIDIA 346.35
[thread 00000001][I][198]:     GLSL version: 4.50 NVIDIA
[thread 00000001][I][198]:     Available texture memory (from NVidia extension): 4194304 kB
[thread 00000001][I][232]: TomCrypt initializing...
[thread 00000001][I][233]: TomCrypt initialized
[thread 00000004][W][233]: eON_HeapSetInformation() - requested heap corruption termination, ignoring
[thread 00000004][W][251]: eON_LoadLibraryEx() couldn't load 'C:\sgraid1\home\mwoodj\.local\share\Steam-HDD\SteamApps\common\the witcher 2\bin\telemetry32.dll', returning NULL!
[thread 00000004][I][5311]: Enumerating COM libraries...

**System Info**

Gentoo 64-bit (kernel: 3.18.4)
Intel Core i7 3770
16GB RAM
GeForce GTX 670

**Comment by eydee** [comment]
OK, I see people keep coming here, so I post the workaround here as well. Credits go to Pontostroy from the Phoronix forums.

In Steam right click the game, select properties, then set launch options. Put this into the field:
MESA_GL_VERSION_OVERRIDE=3.3COMPAT %command%

The game will work fine from this point, including the overlay etc. GL3 is being used.

**Comment by khnazile** [comment]
>Put this into the field:
>MESA_GL_VERSION_OVERRIDE=3.3COMPAT %command%

So, looks like game actually needs OpenGL compatibility profile, which Mesa does not support? There is only core profile for OpenGL>=3.1 in Mesa

**Comment by mwoodj** [comment]
It seems my issue on Gentoo 64-bit is unrelated to this issue. I have an Nvidia card and the temporary solutions mentioned in this thread don't make a difference for me. I was considering adding a new ticket but the title of this one is a bit general and my problem does fall within it.

**Comment by eydee** [comment]
@mwoodj:
The next thing in the log would be sound info, so your game probably crashes due to some sound issues.

**Comment by mwoodj** [comment]
That was a good hint. It seems there is an issue with Witcher 2 and my sound configuration. I am using pure ALSA with a hardware mixing soundcard (no software mixer like dmix and no pulseaudio.) It was working fine with Witcher 2 before the kernel breakage and beta. I haven't changed anything about my sound configuration and other games, including games that use openal, are working fine. If I change my alsoftrc configuration to use the oss driver (alsa oss emulation) the game starts and sound works. If I change it back to alsa the game fails to start again. I may create a new ticket for this issue tomorrow. Thanks.

**Comment by eydee** [comment]
The issue is now fixed for me in the latest public beta. The game can now run with both fglrx and Mesa. Very nice work.
