### ISSUE TITLE
GOG version of the game crashes on fedora 21 x86_64

### ISSUE THREAD

**Issue by Hernanarce** [KillaW0lf04/The-Witcher-2-Issues#97]
I have problems running the GOG version of the game after the launcher.

my eon.txt says only this

[thread ffffffff][I][0]: Log system initialised
[thread ffffffff][I][2]: Default allowed number of simultaneously open files in the system is 500000.
[thread ffffffff][I][2]: Current memlock limit is 65536.
[thread ffffffff][I][2]: setrlimit(RLIMIT_MEMLOCK) failed, (1) Operation not permitted

My crash report http://pastebin.com/nAhLaQAZ

**Comment by vpltd-peterm** [comment]
GOG version will be affected by #89
