### ISSUE TITLE
Game doesn't want to start Manjaro.

### ISSUE THREAD

**Issue by nlhnt** [KillaW0lf04/The-Witcher-2-Issues#98]
Hello, 
Here's my crash report.
Launcher goes fine, untill you click start the game.

    http://pastebin.com/5yzYjV54

Latest omega drivers (amd), phenom II 965 - I know this hardware can barely run it on linux but it used to work, now it doesn't.
Oh my build is: 359285
GPU: Radeon HD 7790 1 GB.

**Comment by eydee** [comment]
In Steam right click the game, select properties, go to the betas tab, and select the public beta. It should solve your issue.

**Comment by nlhnt** [comment]
Thanks, it is working now indeedy :).

**Comment by vpltd-peterm** [comment]
Latest beta was tested with Manjaro and Antergos. This was likely due to #89 which the beta fixes. Closing now.
