### ISSUE TITLE
game dont start (archlinux 64 bit)

### ISSUE THREAD

**Issue by quandasim** [KillaW0lf04/The-Witcher-2-Issues#99]
hi. i wana try the new optimized witcher 2 linux patch (the +20 fps one;) but the game dont start. i tried link some libraries from steam folder to witcher 2 folder, but it dont help,
here is ldd witcher2:
http://108.61.179.153/ldd.txt

here is error code when i try ./witcher2

[quandasim@magi the witcher 2]$ ./witcher2
witcher2: /mnt/Storage/Development/Projects/eon2-witcher2/src/dlls/win32/kernel32/winthreads.cpp:308: int get_selector_for_teb_entries(): Assertion `ret == 0' failed.
CrashReporter: /usr/lib32/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by CrashReporter)

i know archlinux 64 bit is not oficialy supported ( i dont know why) but all others games works without problem. the game was working normaly before update.

thx for any help and sorry for my bad english.

**Comment by vpltd-peterm** [comment]
From that crash report, you are not correctly opted into the beta version

**Comment by quandasim** [comment]
hi, thanks for quick response, your solution works perfectly, now the game works without problem.

thanks for linux support and bye;)
